// This file is automatically generated from your CSS. Any edits will be overwritten.
export const container: string;
export const section: string;
export const nextSection: string;
export const longSection: string;
export const footer: string;
